image: docker:24

stages:
  - build
  - deploy

build-job:
  stage: build
  tags:
    - docker-runner

  script:
    - docker version
    - docker compose version

  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - docker-runner

  needs:
    - build-job

  script:
    - cd /home/ubuntu/docker/Flask-App
    - docker compose down --remove-orphans || true
    - docker compose up -d --build
    - docker ps

  only:
    - main