stages:
  - build
  - deploy

variables:
  DOCKER_HOST: unix:///var/run/docker.sock

build-job:
  stage: build
  tags:
    - docker-runner
  image: docker:24
  script:
    - docker compose build
  only:
    - main

deploy-job:
  stage: deploy
  tags:
    - docker-runner
  image: docker:24
  needs:
    - build-job
  script:
    - docker rm -f postgres-db || true
    - docker rm -f flask-backend || true
    - docker rm -f nginx || true
    - docker compose up -d --build --force-recreate
  only:
    - main
