name: Flask CI CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - uses: actions/checkout@v4

      - run: rsync -av --no-perms --no-owner --no-group ./ /home/ubuntu/docker/Flask-App/
      
      - run: |
          cd /home/ubuntu/docker/Flask-App
          docker compose down --remove-orphans || true
          docker compose up -d --build
          docker ps
